In [1]:
#pip install pandas

In [2]:
#1)Series

In [3]:
import numpy as np
import pandas as pd

In [4]:
s1=pd.Series([4,3,-9,0,8])
s1

0    4
1    3
2   -9
3    0
4    8
dtype: int64

In [5]:
s2=pd.Series([55,12,-5,99],index=["a","c","b","k"])
s2

a    55
c    12
b    -5
k    99
dtype: int64

In [6]:
s1[2]

-9

In [7]:
s2["k"]

99

In [8]:
s2["c"]=60
s2

a    55
c    60
b    -5
k    99
dtype: int64

In [9]:
s1

0    4
1    3
2   -9
3    0
4    8
dtype: int64

In [10]:
s1*2

0     8
1     6
2   -18
3     0
4    16
dtype: int64

In [11]:
d1={"ali":14.5, "reza":17, "bahram":15.44}

In [12]:
s3=pd.Series(d1)
s3

ali       14.50
reza      17.00
bahram    15.44
dtype: float64

In [13]:
d2=s3.to_dict()
d2

{'ali': 14.5, 'reza': 17.0, 'bahram': 15.44}

In [14]:
d1

{'ali': 14.5, 'reza': 17, 'bahram': 15.44}

In [15]:
s4=pd.Series(d1,index=["reza","ali","ahmad"])
s4

reza     17.0
ali      14.5
ahmad     NaN
dtype: float64

In [16]:
s4.isna()

reza     False
ali      False
ahmad     True
dtype: bool

In [17]:
s4.notna()

reza      True
ali       True
ahmad    False
dtype: bool

In [18]:
s2

a    55
c    60
b    -5
k    99
dtype: int64

In [19]:
s5=pd.Series([43,19,5,23,196],index=["b","f","k","a","n"])
s5

b     43
f     19
k      5
a     23
n    196
dtype: int64

In [20]:
s2+s5

a     78.0
b     38.0
c      NaN
f      NaN
k    104.0
n      NaN
dtype: float64

In [21]:
s2

a    55
c    60
b    -5
k    99
dtype: int64

In [22]:
s2["b"]

-5

In [23]:
# s2[2] FutureWarning

In [24]:
s2.index[2]

'b'

In [25]:
# s2.index[2]="f" TypeError

In [26]:
s2

a    55
c    60
b    -5
k    99
dtype: int64

In [27]:
s2.index=["p","f","r","c"]
s2

p    55
f    60
r    -5
c    99
dtype: int64

In [28]:
s2.name="numbers"
s2.index.name="indexs"
s2

indexs
p    55
f    60
r    -5
c    99
Name: numbers, dtype: int64

In [29]:
#2)DataFrame

In [30]:
d3={"state":["tehran","tehran","tehran","lorestan","lorstan","lorstan"],
    "year":[1375,1385,1395,1385,1395,1404],
    "pop":[10.1,11.5,13.7,1.2,1.9,1.8]}

In [31]:
df1=pd.DataFrame(d3)
df1

      state  year   pop
0    tehran  1375  10.1
1    tehran  1385  11.5
2    tehran  1395  13.7
3  lorestan  1385   1.2
4   lorstan  1395   1.9
5   lorstan  1404   1.8

In [32]:
df1.head(3)

    state  year   pop
0  tehran  1375  10.1
1  tehran  1385  11.5
2  tehran  1395  13.7

In [33]:
df1.tail(2)

     state  year  pop
4  lorstan  1395  1.9
5  lorstan  1404  1.8

In [34]:
df1

      state  year   pop
0    tehran  1375  10.1
1    tehran  1385  11.5
2    tehran  1395  13.7
3  lorestan  1385   1.2
4   lorstan  1395   1.9
5   lorstan  1404   1.8

In [35]:
df1["year"]

0    1375
1    1385
2    1395
3    1385
4    1395
5    1404
Name: year, dtype: int64

In [36]:
df1.year

0    1375
1    1385
2    1395
3    1385
4    1395
5    1404
Name: year, dtype: int64

In [37]:
df1

      state  year   pop
0    tehran  1375  10.1
1    tehran  1385  11.5
2    tehran  1395  13.7
3  lorestan  1385   1.2
4   lorstan  1395   1.9
5   lorstan  1404   1.8

In [38]:
df2=pd.DataFrame(d3,columns=["pop","state","year","debt"])
df2

    pop     state  year debt
0  10.1    tehran  1375  NaN
1  11.5    tehran  1385  NaN
2  13.7    tehran  1395  NaN
3   1.2  lorestan  1385  NaN
4   1.9   lorstan  1395  NaN
5   1.8   lorstan  1404  NaN

In [39]:
df2["debt"]=2
df2

    pop     state  year  debt
0  10.1    tehran  1375     2
1  11.5    tehran  1385     2
2  13.7    tehran  1395     2
3   1.2  lorestan  1385     2
4   1.9   lorstan  1395     2
5   1.8   lorstan  1404     2

In [40]:
df2["debt"]=np.arange(1,7)
df2

    pop     state  year  debt
0  10.1    tehran  1375     1
1  11.5    tehran  1385     2
2  13.7    tehran  1395     3
3   1.2  lorestan  1385     4
4   1.9   lorstan  1395     5
5   1.8   lorstan  1404     6

In [41]:
del df2["debt"]
df2

    pop     state  year
0  10.1    tehran  1375
1  11.5    tehran  1385
2  13.7    tehran  1395
3   1.2  lorestan  1385
4   1.9   lorstan  1395
5   1.8   lorstan  1404

In [42]:
d4={"lorstan":{1385:1.2,1395:1.6,1404:1.5},
    "tehran":{1385:13.2,1395:14.1,1402:13.9}}
df3=pd.DataFrame(d4)
df3

      lorstan  tehran
1385      1.2    13.2
1395      1.6    14.1
1404      1.5     NaN
1402      NaN    13.9

In [43]:
df3.T

         1385  1395  1404  1402
lorstan   1.2   1.6   1.5   NaN
tehran   13.2  14.1   NaN  13.9

In [44]:
df3.index.name="year"
df3.columns.name="state"
df3

state  lorstan  tehran
year
1385       1.2    13.2
1395       1.6    14.1
1404       1.5     NaN
1402       NaN    13.9

In [45]:
n1=df3.to_numpy()
n1

array([[ 1.2, 13.2],
       [ 1.6, 14.1],
       [ 1.5,  nan],
       [ nan, 13.9]])

In [46]:
n1.dtype

dtype('float64')

In [47]:
s2

indexs
p    55
f    60
r    -5
c    99
Name: numbers, dtype: int64

In [48]:
#عملیات های ضروری
#1) reindex

In [49]:
s6=pd.Series([3,46,11,7],index=["b","d","a","f"])
s6

b     3
d    46
a    11
f     7
dtype: int64

In [50]:
s7=s6.reindex(index=list("abcdef"))
s7

a    11.0
b     3.0
c     NaN
d    46.0
e     NaN
f     7.0
dtype: float64

In [51]:
s8=pd.Series(["ali","reza","ahmad"], index=[0,2,4])
s8

0      ali
2     reza
4    ahmad
dtype: object

In [52]:
s9=s8.reindex(index=np.arange(5),method="bfill") #,method="ffill"
s9

0      ali
1     reza
2     reza
3    ahmad
4    ahmad
dtype: object

In [53]:
s9

0      ali
1     reza
2     reza
3    ahmad
4    ahmad
dtype: object

In [54]:
s9.drop([1,3])

0      ali
2     reza
4    ahmad
dtype: object

In [55]:
df3

state  lorstan  tehran
year
1385       1.2    13.2
1395       1.6    14.1
1404       1.5     NaN
1402       NaN    13.9

In [56]:
df4=df3.drop(columns=["tehran"])
df4

state  lorstan
year
1385       1.2
1395       1.6
1404       1.5
1402       NaN

In [57]:
s10=pd.Series([54,11,-8,0,4], index=list("abcde"))
s10

a    54
b    11
c    -8
d     0
e     4
dtype: int64

In [58]:
s10["c"]

-8

In [59]:
# s10[2] FutureWarning

In [60]:
s11=pd.Series([1,2,3], index=[20,310,11])
s11

20     1
310    2
11     3
dtype: int64

In [61]:
#s11[0]  KeyError

In [62]:
s10

a    54
b    11
c    -8
d     0
e     4
dtype: int64

In [63]:
s10.loc["d"]

0

In [64]:
#s10.loc[1] KeyError

In [65]:
s10.iloc[3]

0

In [66]:
df5=pd.DataFrame(np.arange(16).reshape(4,4),
                 index=["shiraz","yazd","tehran","kerman"],
                 columns=["one","two","three","four"])
df5

        one  two  three  four
shiraz    0    1      2     3
yazd      4    5      6     7
tehran    8    9     10    11
kerman   12   13     14    15

In [67]:
df5["four"]

shiraz     3
yazd       7
tehran    11
kerman    15
Name: four, dtype: int32

In [68]:
df5[["four","one"]]

        four  one
shiraz     3    0
yazd       7    4
tehran    11    8
kerman    15   12

In [69]:
df5

        one  two  three  four
shiraz    0    1      2     3
yazd      4    5      6     7
tehran    8    9     10    11
kerman   12   13     14    15

In [70]:
df5[:"tehran"]

        one  two  three  four
shiraz    0    1      2     3
yazd      4    5      6     7
tehran    8    9     10    11

In [71]:
df5

        one  two  three  four
shiraz    0    1      2     3
yazd      4    5      6     7
tehran    8    9     10    11
kerman   12   13     14    15

In [72]:
#df1.loc[#index , columns ]

In [73]:
df5.loc[["shiraz","kerman"]]

        one  two  three  four
shiraz    0    1      2     3
kerman   12   13     14    15

In [74]:
df5

        one  two  three  four
shiraz    0    1      2     3
yazd      4    5      6     7
tehran    8    9     10    11
kerman   12   13     14    15

In [75]:
df5.loc[["yazd","tehran"],["two","three"]]

        two  three
yazd      5      6
tehran    9     10

In [76]:
df5[(df5<6) | (df5>10)]=0
df5

        one  two  three  four
shiraz    0    0      0     0
yazd      0    0      6     7
tehran    8    9     10     0
kerman    0    0      0     0