In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Employees.csv")
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,-,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,?,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,0.0,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,n.a.,PhD,physics,19,6300

In [3]:
MissingData=[0,"?","-","n.a.","NA"]

In [4]:
df=pd.read_csv("Employees.csv",na_values=MissingData)
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [5]:
df.dropna(axis=0,how="any",inplace=False)

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900

In [6]:
df.dropna(axis=1,how="any",inplace=False)

     ID     Name   Family  Gender  Workday  Salary
0  1001      ali  nosrati    male       21    4500
1  1290     reza  bahmani    male       18    3400
2  1211    zahra  farhadi  female       19    3900
3  1599    hadis  sohrabi  female       28    4800
4  1441    saber   tohidi    male       14    5800
5  1733    kazem     yari    male       10    3100
6  1930  fatemeh  bagheri  female       20    5500
7  1322   bahram   karimi    male       25    5200
8  1870   narges  rahmati  female       23    5900
9  1655    hamed  sadeghi    male       19    6300

In [7]:
df["test1"]=np.nan
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary,test1
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500,NaN
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400,NaN
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900,NaN
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800,NaN
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800,NaN
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100,NaN
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500,NaN
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200,NaN
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900,NaN
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300,NaN

In [8]:
df.dropna(axis=1,how="all",inplace=True)
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [9]:
df["Age"].fillna(df["Age"].mean(),inplace=False)
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [10]:
df["Age"].fillna(20,inplace=False)

0    41.0
1    34.0
2    20.0
3    25.0
4    32.0
5    20.0
6    50.0
7    21.0
8    37.0
9    49.0
Name: Age, dtype: float64

In [11]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [12]:
df["Speciality"].ffill(inplace=False)

0      computer
1      computer
2       physics
3      computer
4           art
5           law
6    accounting
7           art
8      computer
9       physics
Name: Speciality, dtype: object

In [13]:
df["Speciality"].bfill(inplace=False)

0      computer
1       physics
2       physics
3      computer
4           art
5           law
6    accounting
7           art
8      computer
9       physics
Name: Speciality, dtype: object

In [14]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [15]:
df["Age"].interpolate(method="linear",inplace=False)

0    41.0
1    34.0
2    29.5
3    25.0
4    32.0
5    41.0
6    50.0
7    21.0
8    37.0
9    49.0
Name: Age, dtype: float64

In [16]:
df["Age"].interpolate(method="polynomial",order=2,inplace=False)

0    41.000000
1    34.000000
2    27.198244
3    25.000000
4    32.000000
5    49.335040
6    50.000000
7    21.000000
8    37.000000
9    49.000000
Name: Age, dtype: float64

In [17]:
df.to_csv("file1.csv",index=False)

In [18]:
df.to_excel("file2.xlsx",index=False, sheet_name="کارمندان")

In [19]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [20]:
df[["Name","Family","Age"]]

      Name   Family   Age
0      ali  nosrati  41.0
1     reza  bahmani  34.0
2    zahra  farhadi   NaN
3    hadis  sohrabi  25.0
4    saber   tohidi  32.0
5    kazem     yari   NaN
6  fatemeh  bagheri  50.0
7   bahram   karimi  21.0
8   narges  rahmati  37.0
9    hamed  sadeghi  49.0

In [21]:
df.loc[:,["Name","Family","Age"]]

      Name   Family   Age
0      ali  nosrati  41.0
1     reza  bahmani  34.0
2    zahra  farhadi   NaN
3    hadis  sohrabi  25.0
4    saber   tohidi  32.0
5    kazem     yari   NaN
6  fatemeh  bagheri  50.0
7   bahram   karimi  21.0
8   narges  rahmati  37.0
9    hamed  sadeghi  49.0

In [22]:
df.iloc[:,[1,2,4]]

      Name   Family   Age
0      ali  nosrati  41.0
1     reza  bahmani  34.0
2    zahra  farhadi   NaN
3    hadis  sohrabi  25.0
4    saber   tohidi  32.0
5    kazem     yari   NaN
6  fatemeh  bagheri  50.0
7   bahram   karimi  21.0
8   narges  rahmati  37.0
9    hamed  sadeghi  49.0

In [23]:
df.loc[:,"Family":"City"]

    Family  Gender   Age         City
0  nosrati    male  41.0       tehran
1  bahmani    male  34.0         yazd
2  farhadi  female   NaN       tehran
3  sohrabi  female  25.0          NaN
4   tohidi    male  32.0  khorramabad
5     yari    male   NaN       kashan
6  bagheri  female  50.0       tehran
7   karimi    male  21.0         yazd
8  rahmati  female  37.0       kashan
9  sadeghi    male  49.0          NaN

In [24]:
df.head(3)

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900

In [25]:
df.tail(3)

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [26]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [27]:
df.loc[df["Gender"]=="male",["Family","Workday"]]

    Family  Workday
0  nosrati       21
1  bahmani       18
4   tohidi       14
5     yari       10
7   karimi       25
9  sadeghi       19

In [28]:
df.loc[df["Age"]>40,["Family","Speciality"]]

    Family  Speciality
0  nosrati    computer
6  bagheri  accounting
9  sadeghi     physics

In [29]:
df.loc[(df["City"]=="tehran") | (df["City"]=="yazd")]

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200

In [30]:
df.loc[df["City"].isin(["tehran","yazd"])]

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200

In [31]:
df.loc[(df["Speciality"]=="computer") & (df["Workday"]>25)]

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800

In [32]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [33]:
gr1=df.groupby("Gender")

In [34]:
gr1.groups

{'female': [2, 3, 6, 8], 'male': [0, 1, 4, 5, 7, 9]}

In [37]:
for name_g,member_g in gr1[["Name","Family","Age"]]:
    print(name_g)
    print(member_g)

female
      Name   Family   Age
2    zahra  farhadi   NaN
3    hadis  sohrabi  25.0
6  fatemeh  bagheri  50.0
8   narges  rahmati  37.0
male
     Name   Family   Age
0     ali  nosrati  41.0
1    reza  bahmani  34.0
4   saber   tohidi  32.0
5   kazem     yari   NaN
7  bahram   karimi  21.0
9   hamed  sadeghi  49.0

In [38]:
df

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
0,1001,ali,nosrati,male,41.0,tehran,Bachelor,computer,21,4500
1,1290,reza,bahmani,male,34.0,yazd,Bachelor,NaN,18,3400
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
3,1599,hadis,sohrabi,female,25.0,NaN,Bachelor,computer,28,4800
4,1441,saber,tohidi,male,32.0,khorramabad,PhD,art,14,5800
5,1733,kazem,yari,male,NaN,kashan,NaN,law,10,3100
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
7,1322,bahram,karimi,male,21.0,yazd,Bachelor,art,25,5200
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900
9,1655,hamed,sadeghi,male,49.0,NaN,PhD,physics,19,6300

In [42]:
gr2=df.groupby("Degree")
gr2.groups

{'Bachelor': [0, 1, 3, 7], 'Master': [2, 6, 8], 'PhD': [4, 9]}

In [43]:
gr3=df.groupby(["Gender","Degree"])
gr3.groups

{('female', 'Bachelor'): [3], ('female', 'Master'): [2, 6, 8], ('male', 'Bachelor'): [0, 1, 7], ('male', 'PhD'): [4, 9], ('male', nan): [5]}

In [44]:
gr2.get_group("Master")

,ID,Name,Family,Gender,Age,City,Degree,Speciality,Workday,Salary
2,1211,zahra,farhadi,female,NaN,tehran,Master,physics,19,3900
6,1930,fatemeh,bagheri,female,50.0,tehran,Master,accounting,20,5500
8,1870,narges,rahmati,female,37.0,kashan,Master,computer,23,5900

In [45]:
gr1.count()

        ID  Name  Family  Age  City  Degree  Speciality  Workday  Salary
Gender
female   4     4       4    3     3       4           4        4       4
male     6     6       6    5     5       5           5        6       6

In [46]:
gr1.size()

Gender
female    4
male      6
dtype: int64

In [48]:
gr1["Age"].mean()

Gender
female    37.333333
male      35.400000
Name: Age, dtype: float64

In [49]:
gr1["Age"].max()

Gender
female    50.0
male      49.0
Name: Age, dtype: float64

In [50]:
gr1["Age"].min()

Gender
female    25.0
male      21.0
Name: Age, dtype: float64

In [51]:
gr1["Age"].agg(["min","max","mean","count"])

         min   max       mean  count
Gender
female  25.0  50.0  37.333333      3
male    21.0  49.0  35.400000      5

In [52]:
gr2["Age"].agg(["min","max","mean","count"])

           min   max   mean  count
Degree
Bachelor  21.0  41.0  30.25      4
Master    37.0  50.0  43.50      2
PhD       32.0  49.0  40.50      2